version: '3'

services:
    pgsql:
      image: albulenpano/test1
      env_file: .env
      container_name: ontop_pgsql_running
      ports: 
        - "7777:5432"
      environment: 
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
