version: '3'

services:
    pgsql:
      image: ontop/ontop-pgsql
      env_file: .env
      container_name: ontop_pgsql_running
      ports: 
        - "7777:5432"
      environment: 
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    oracle:
      build: ./oracle
      env_file: .env
      container_name: ontop_oracle_running
      ports:
        - "49160:8080"
        - "49161:1521"
      environment:
        - LICENSE=accept
        
    mssql:
      image: ontop/ontop-mssql
      env_file: .env
      container_name: ontop_mssql_running
      ports:
        - "1533:1433"
      environment:
        - SA_PASSWORD=${SA_PASSWORD}
        - ACCEPT_EULA=Y

    mysql:
      image: ontop/ontop-mysql
      env_file: .env
      container_name: ontop_mysql_running
      ports:
       - "3694:3306"
      environment:
       - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

    db2:
      image: ontop/ontop-db2
      env_file: .env 
      container_name: ontop_db2_running
      privileged: true
      ports:
        - "50000:50000"
      environment:
       - DB2INST1_PASSWORD=${DB2INST1_PASSWORD}
       - LICENSE=accept
      
