version: '3'

services:
    pgsql:
      image: ontop_pgsql
      build: ./pgsql
      container_name: ontop_pgsql_running
      ports: 
        - "7777:5432"
      environment: 
        - POSTGRES_PASSWORD=postgres2

    oracle:
      image: ontop_oracle
      build: ./oracle
      container_name: ontop_oracle_running
      ports:
        - "49160:8080"
        - "49161:1521"

    mssql:
      image: ontop_mssql
      build: ./mssql
      container_name: ontop_mssql_running
      ports:
        - "1533:1433"
      environment:
        - SA_PASSWORD=Mssql1.0
        - ACCEPT_EULA=Y

    mysql:
      image: ontop_mysql
      build: ./mysql
      container_name: ontop_mysql_running
      ports:
       - "3694:3306"
      environment:
       - MYSQL_ROOT_PASSWORD=mysql

    db2:
      image: ontop_db2
      build: ./db2
      container_name: ontop_db2_running
      privileged: true
      ports:
        - "50000:50000"
      environment:
       - DB2INST1_PASSWORD=obda-pwd
       - LICENSE=accept
      