CREATE DATABASE "DBCONSTRAINTS:;

CREATE TABLE "DBCONSTRAINTS"."BOOK"
   (	"BK_CODE" NUMBER(*,0),
	"BK_TITLE" VARCHAR2(100),
   ) ;
   
ALTER TABLE "DBCONSTRAINTS"."BOOK" ADD CONSTRAINT "PK_BOOK" PRIMARY KEY ("BK_CODE") ENABLE;
   
CREATE TABLE "DBCONSTRAINTS"."BOOKWRITER"
   (	"BK_CODE" NUMBER(*,0),
	"WR_CODE" NUMBER(*,0),
   ) ;

ALTER TABLE "DBCONSTRAINTS"."BOOKWRITER" ADD CONSTRAINT "FK_BOOK_WRITER" FOREIGN KEY ("BK_CODE")
	  REFERENCES "DBCONSTRAINTS"."BOOK" ("BK_CODE") ENABLE;
ALTER TABLE "DBCONSTRAINTS"."BOOKWRITER" ADD CONSTRAINT "FK_WRITER_BOOK" FOREIGN KEY ("WR_CODE")
	  REFERENCES "DBCONSTRAINTS"."WRITER" ("WR_CODE") ENABLE;
   
CREATE TABLE "DBCONSTRAINTS"."EDITION"
   (	"ED_CODE" NUMBER(*,0),
	"ED_YEAR" NUMBER(*,0),
	"BK_CODE" NUMBER(*,0),
   ) ;

ALTER TABLE "DBCONSTRAINTS"."EDITION" ADD CONSTRAINT "PK_EDITION" PRIMARY KEY ("ED_CODE") ENABLE;
ALTER TABLE "DBCONSTRAINTS"."EDITION" ADD CONSTRAINT "FK_BOOK_EDITION" FOREIGN KEY ("BK_CODE")
	  REFERENCES "DBCONSTRAINTS"."BOOK" ("BK_CODE") ENABLE;
	  
CREATE TABLE "DBCONSTRAINTS"."WRITER"
   (	"WR_CODE" NUMBER(*,0),
	"WR_NAME" VARCHAR2(100),
   ) ;
   
ALTER TABLE "DBCONSTRAINTS"."WRITER" ADD CONSTRAINT "PK_WRITER" PRIMARY KEY ("WR_CODE") ENABLE;
