CREATE DATABASE DBCONSTRAINTS;

CONNECT TO DBCONSTRAINTS;

CREATE TABLE "BOOK" (
"BK_CODE" INTEGER NOT NULL,
"BK_TITLE" VARCHAR(100) WITH DEFAULT NULL,
PRIMARY KEY ("BK_CODE")
) ;
		
CREATE TABLE "BOOKWRITER" (
"BK_CODE" INTEGER NOT NULL,
"WR_CODE" INTEGER WITH DEFAULT NULL,
FOREIGN KEY ("BK_CODE") REFERENCES "BOOK"("BK_CODE"),
FOREIGN KEY ("WR_CODE") REFERENCES "WRITER"("WR_CODE")
) ;

CREATE TABLE "EDITION" (
"ED_CODE" INTEGER NOT NULL,
"ED_YEAR" INTEGER WITH DEFAULT NULL,
"BK_CODE" INTEGER WITH DEFAULT NULL,
PRIMARY KEY ("PK_EDITION"),
FOREIGN KEY ("BK_CODE") REFERENCES "BOOK"("BK_CODE")
) ;

CREATE TABLE "WRITER" (
"WR_CODE" INTEGER NOT NULL,
"WR_NAME" VARCHAR(100) WITH DEFAULT NULL,
PRIMARY KEY ("PK_WRITER")
) ;
