version: '3'

services:
  dremio:
    build: ./
    container_name: ontop_dremio_running
    ports:
      - "9047:9047"
      - "31010:31010"
      - "45678:45678"

  pgsql:
    image: ontop/ontop-pgsql
    env_file: .env
    container_name: ontop_pgsql_running
    ports: 
      - "7777:5432"
    environment: 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  mysql:
    image: ontop/ontop-mysql
    env_file: .env
    container_name: ontop_mysql_running
    ports:
      - "3694:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  mssql:
    image: ontop/ontop-mssql
    env_file: .env
    container_name: ontop_mssql_running
    ports:
      - "1533:1433"
    environment:
      - SA_PASSWORD=${SA_PASSWORD}
      - ACCEPT_EULA=Y

  oracle:
    build: ./../oracle
    env_file: .env
    container_name: ontop_oracle_running
    ports:
      - "49160:8080"
      - "49161:1521"
    environment:
      - ORACLE_PASSWORD=oracle
      - LICENSE=accept
  
  #IBM DB2 connector is not supported anymore by Dremio

